name: Lint & Test
on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Configure git
        run: git config --global core.autocrlf false # required on Windows
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: golangci/golangci-lint-action@v7
        with:
          skip-cache: true
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      POSTGRES_USER: indexd_test
      POSTGRES_PASSWORD: indexd_test
      POSTGRES_DB: indexd_test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Test
        uses: n8maninger/action-golang-test@v2
        with:
          args: -race;-failfast
