name: Publish

# Controls when the action will run.
on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  test:
    permissions:
      contents: read
    uses: ./.github/workflows/go-test.yml
  docker:
    name: Publish Docker
    needs:
      - test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./cmd/junkd
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/siafoundation/junkd:master
          cache-from: type=gha
          cache-to: type=gha,mode=max
